let cartoes =
 criaCartao( 'Personagens', 'Quem é o protagonista do filme Shrek?', 'O protagonista é o ogro Shrek.' );
 criaCartao( 'Trilha sonora', 'Qual é a música mais marcante da trilha sonora de Shrek?', 'A música "All Star" da banda Smash Mouth.' );
 criaCartao( 'Enredo', 'Qual é a missão de Shrek no primeiro filme?', 'Ele deve resgatar a Princesa Fiona para o Lorde Farquaad.' );
 criaCartao( 'Coadjuvante', 'Quem é o melhor amigo de Shrek?', 'O Burro.' );
 criaCartao( 'Romance', 'Quem é o interesse amoroso de Shrek?', 'A Princesa Fiona.' );
 criaCartao( 'Vilão', 'Quem é o vilão principal do primeiro filme?', 'Lorde Farquaad.' );
criaCartao( 'Transformação', 'Que segredo Fiona esconde?', 'Ela se transforma em ogra à noite devido a uma maldição.' );
criaCartao( 'Ambiente', 'Onde Shrek vive no início do filme?', 'Em um pântano.' );
criaCartao( 'Lançamento', 'Em que ano o filme Shrek foi lançado?', 'Em 2001.' );
criaCartao( 'Dublagem', 'Quem faz a voz de Shrek na versão original?', 'Mike Myers.' );
criaCartao( 'Humor', 'Que tipo de humor é mais presente no filme Shrek?', 'Humor satírico e irônico.' );
criaCartao( 'Reino', 'Como se chama o reino de Lorde Farquaad?', 'Duloc.' );
criaCartao( 'Dragão', 'O que guarda a torre onde Fiona está presa?', 'Um dragão.' );
criaCartao( 'Surpresa', 'Quem o Dragão acaba se apaixonando?', 'Pelo Burro.' );
criaCartao( 'Moral', 'Qual é a principal lição do filme Shrek?', 'Aceitar a si mesmo e aos outros como são.' );
criaCartao( 'Gênero', 'Qual é o gênero principal de Shrek?', 'Animação de comédia e aventura.' );
criaCartao( 'Aparência', 'Como Shrek é fisicamente?', 'Ele é um ogro grande, verde e com orelhas pontudas.' );
criaCartao( 'Contos de fadas', 'Quais figuras clássicas de contos de fadas aparecem no filme?', 'Pinóquio, Três Porquinhos, Lobo Mau e outros.' );
criaCartao( 'Origem', 'Em que estúdio Shrek foi produzido?', 'No estúdio DreamWorks Animation.' );
criaCartao( 'Popularidade', 'Shrek ganhou algum Oscar?', 'Sim, venceu o Oscar de Melhor Filme de Animação em 2002.' );
criaCartao( 'Trilha sonora', 'Quem canta a música "Hallelujah" no filme?', 'Rufus Wainwright.' );
criaCartao( 'Trilogia', 'Quantos filmes existem na franquia principal de Shrek?', 'Quatro filmes.' );
criaCartao( 'Sequência', 'Qual é o título do segundo filme de Shrek?', 'Shrek 2.' );
criaCartao( 'Comédia', 'Que personagem é conhecido por falar sem parar?', 'O Burro.' );
criaCartao( 'Paródia', 'Shrek é uma paródia de qual gênero?', 'Contos de fadas.' );
criaCartao( 'Princesa', 'Qual era o objetivo de Fiona antes de conhecer Shrek?', 'Casar com um príncipe encantado.' );
criaCartao( 'Animal', 'Que animal é o Burro?', 'Um burro falante.' );
criaCartao( 'Espelho mágico', 'Que função o Espelho Mágico desempenha no filme?', 'Ajuda Farquaad a escolher uma princesa para casar.' );
criaCartao( 'Referências', 'Que outros filmes Shrek parodia?', 'Inclui referências a Matrix, Homem-Aranha e outros.' );
criaCartao( 'Cena inicial', 'Que música toca na introdução do filme?', 'A música "All Star" da banda Smash Mouth.' );
criaCartao( 'Livro', 'O filme Shrek foi inspirado em quê?', 'Em um livro infantil de William Steig.' );
criaCartao( 'Criaturas mágicas', 'O que acontece com as criaturas mágicas no filme?', 'Elas são expulsas para o pântano de Shrek.' );
criaCartao( 'Príncipe', 'Por que Farquaad quer se casar com Fiona?', 'Para se tornar rei de Duloc.' );
criaCartao( 'Transformação final', 'Qual forma Fiona escolhe no final?', 'Ela escolhe permanecer como ogra.' );
criaCartao( 'Amigos', 'Como Shrek e o Burro se tornam amigos?', 'Após se ajudarem a salvar as criaturas mágicas.' );
criaCartao( 'Romance', 'Por que Shrek e Fiona se apaixonam?', 'Eles se conectam ao perceberem que são parecidos.' );
criaCartao( 'Sequência', 'Qual personagem novo é apresentado em Shrek 2?', 'O Gato de Botas.' );
criaCartao( 'Criador', 'Quem dirigiu o primeiro filme Shrek?', 'Andrew Adamson e Vicky Jenson.' );
criaCartao( 'Mensagem', 'Qual é a principal mensagem de Shrek?', 'A verdadeira beleza está no interior.' );
criaCartao( 'Comida', 'Qual é a comida favorita de Shrek?', 'Sopa de olho e outros pratos estranhos.' );
criaCartao( 'Título', 'O que significa o nome "Shrek"?', 'Vem da palavra alemã "Schreck", que significa "susto" ou "terror".' );
criaCartao( 'Cenário', 'Qual é o local de destaque em Duloc?', 'O castelo de Farquaad.' );
criaCartao( 'Personagens clássicos', 'Quem é o vilão em Shrek 2?', 'Fada Madrinha.' );
criaCartao( 'Aventura', 'Quem ajuda Shrek na missão de salvar Fiona?', 'O Burro.' );
criaCartao( 'Tecnologia', 'Que técnica inovadora foi usada no filme?', 'Animação por computador 3D avançada.' );
criaCartao( 'Bilheteria', 'O primeiro filme foi um sucesso de bilheteria?', 'Sim, arrecadou mais de 484 milhões de dólares.' );
criaCartao( 'Burro', 'Quem faz a voz do Burro na versão original?', 'Eddie Murphy.' );
criaCartao( 'Cultura pop', 'Shrek influenciou a cultura pop?', 'Sim, tornou-se um ícone com vários memes e adaptações.' );
